// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/captcha": {
            "get": {
                "description": "获取验证码 GetCaptcha",
                "produces": [
                    "application/json"
                ],
                "summary": "获取验证码",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.ResultContCaptcha"
                        }
                    }
                }
            }
        },
        "/captcha/verify/{captchaId}/{value}": {
            "get": {
                "description": "获取验证码 GetCaptcha",
                "produces": [
                    "application/json"
                ],
                "summary": "验证 验证码码图",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "验证码Id",
                        "name": "captchaId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "验证码value",
                        "name": "value",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.ResultContVerifyCaptcha"
                        }
                    }
                }
            }
        },
        "/captcha/{captchaId}": {
            "get": {
                "description": "获取验证码 GetCaptcha",
                "produces": [
                    "application/json"
                ],
                "summary": "获取验证码图片",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "验证码Id",
                        "name": "captchaId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.ResultContGetCaptchaImage"
                        }
                    }
                }
            }
        },
        "/changepass": {
            "put": {
                "description": "输入用户名及密登录",
                "produces": [
                    "application/json"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户邮箱",
                        "name": "email",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "旧密码",
                        "name": "oldpassword",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新密码",
                        "name": "newpassword",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "确认新密码",
                        "name": "confirmpassword",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.ResultContChangePass"
                        }
                    }
                }
            }
        },
        "/index/goodslist": {
            "get": {
                "description": "显示商品列表",
                "produces": [
                    "application/json"
                ],
                "summary": "商品列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分类id",
                        "name": "categoryId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.ResultContGoodsList"
                        }
                    }
                }
            }
        },
        "/index/goodsone/{goodsid}": {
            "get": {
                "description": "显示商品的详情",
                "produces": [
                    "application/json"
                ],
                "summary": "商品详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品id",
                        "name": "goodsid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.ResultContGoods"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "输入用户名及密登录",
                "produces": [
                    "application/json"
                ],
                "summary": "系统超级管理登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录名",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "登录密码",
                        "name": "password",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.ResultContSingIn"
                        }
                    }
                }
            }
        },
        "/singin": {
            "post": {
                "description": "输入用户名及密登录",
                "produces": [
                    "application/json"
                ],
                "summary": "系统登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "承租",
                        "name": "tenant",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "登录名",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "登录密码",
                        "name": "password",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.ResultContSingIn"
                        }
                    }
                }
            }
        },
        "/singup": {
            "post": {
                "description": "输入用户名及密登录",
                "produces": [
                    "application/json"
                ],
                "summary": "注册用户",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "承租户tenant_id",
                        "name": "tenant_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户邮箱",
                        "name": "email",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "登录名",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "登录密码",
                        "name": "password",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.ResultContSingUp"
                        }
                    }
                }
            }
        },
        "/tenant": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "显示承租户详情",
                "produces": [
                    "application/json"
                ],
                "summary": "获取所有承租户详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "承租pageNo",
                        "name": "pageNo",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "承租pageSize",
                        "name": "pageSize",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.ResultContGetTenantList"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "输入承租户名及描述",
                "produces": [
                    "application/json"
                ],
                "summary": "修改承租户",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "承租户tenant_id",
                        "name": "tenant_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "承租户名",
                        "name": "tenant_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "承租户描述",
                        "name": "tenant_des",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "云计算技术和服务提供商",
                        "name": "cctasp",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "承租起始日期",
                        "name": "start_at",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "承租到期日期",
                        "name": "due_at",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "1/true禁用当前记录",
                        "name": "disabled_is",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.ResultContUpdateTenant"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "输入承租户名及描述",
                "produces": [
                    "application/json"
                ],
                "summary": "创建承租户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "承租户名",
                        "name": "tenant_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "承租户描述",
                        "name": "tenant_des",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "云计算技术和服务提供商",
                        "name": "cctasp",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "承租起始日期",
                        "name": "start_at",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "承租到期日期",
                        "name": "due_at",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.ResultContCreatedTenant"
                        }
                    }
                }
            }
        },
        "/tenant/name/{tenant_name}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "显示承租户详情",
                "produces": [
                    "application/json"
                ],
                "summary": "用tenant_name获取承租户详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "承租tenant_name",
                        "name": "tenant_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.ResultContGetTenantByName"
                        }
                    }
                }
            }
        },
        "/tenant/{tenant_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "显示承租户详情",
                "produces": [
                    "application/json"
                ],
                "summary": "用tenant_id获取承租户详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "承租id",
                        "name": "tenant_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.ResultContGetTenantById"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除承租户",
                "produces": [
                    "application/json"
                ],
                "summary": "删除承租户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "承租id",
                        "name": "tenant_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.ResultContDeleteTenantById"
                        }
                    }
                }
            }
        },
        "/test": {
            "get": {
                "description": "Test===",
                "produces": [
                    "application/json"
                ],
                "summary": "Test",
                "parameters": [
                    {
                        "type": "string",
                        "description": "check_in",
                        "name": "check_in",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "check_out",
                        "name": "check_out",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.ResultContTest"
                        }
                    }
                }
            }
        },
        "/token": {
            "get": {
                "description": "获取Token",
                "produces": [
                    "application/json"
                ],
                "summary": "取Token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "承租",
                        "name": "tenant",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "登录名",
                        "name": "user",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "登录密码",
                        "name": "password",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.ResultContToken"
                        }
                    }
                }
            },
            "post": {
                "description": "获取Token",
                "produces": [
                    "application/json"
                ],
                "summary": "生成Token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "承租",
                        "name": "tenant",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "登录名",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "登录密码",
                        "name": "password",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.ResultContToken"
                        }
                    }
                }
            }
        },
        "/user/email/{email}": {
            "get": {
                "description": "显示用户的详情",
                "produces": [
                    "application/json"
                ],
                "summary": "用户详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户email",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.ResultContUserByEmail"
                        }
                    }
                }
            }
        },
        "/user/name/{name}": {
            "get": {
                "description": "显示用户的详情",
                "produces": [
                    "application/json"
                ],
                "summary": "用户详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.ResultContUserByName"
                        }
                    }
                }
            }
        },
        "/user/tenant/{tenant_id}": {
            "get": {
                "description": "显示用户列表",
                "produces": [
                    "application/json"
                ],
                "summary": "用户列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分类id",
                        "name": "tenant_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.ResultContUserByTenantId"
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "get": {
                "description": "显示用户的详情",
                "produces": [
                    "application/json"
                ],
                "summary": "用户详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swag.ResultContUserById"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CaptchaResponse": {
            "type": "object",
            "properties": {
                "captchaId": {
                    "description": "验证码Id",
                    "type": "string"
                },
                "imageUrl": {
                    "description": "验证码图片url",
                    "type": "string"
                }
            }
        },
        "models.Goods": {
            "type": "object",
            "properties": {
                "goodsId": {
                    "description": "商品id",
                    "type": "integer"
                },
                "goodsName": {
                    "description": "商品名字",
                    "type": "string"
                },
                "price": {
                    "description": "商品价格",
                    "type": "string"
                },
                "stock": {
                    "description": "商品库存",
                    "type": "integer"
                },
                "subject": {
                    "description": "商品描述",
                    "type": "string"
                }
            }
        },
        "models.Tenant": {
            "type": "object",
            "required": [
                "tenant_name"
            ],
            "properties": {
                "cctasp": {
                    "description": "云计算技术和服务提供商",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间戳",
                    "type": "integer"
                },
                "disabled_is": {
                    "description": "1:禁用当前记录",
                    "type": "integer"
                },
                "due_at": {
                    "description": "承租到期日期",
                    "type": "string"
                },
                "id": {
                    "description": "承租户id",
                    "type": "integer"
                },
                "start_at": {
                    "description": "承租起始日期",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "string"
                },
                "tenant_des": {
                    "description": "承租户描述",
                    "type": "string"
                },
                "tenant_id": {
                    "description": "承租户uuid",
                    "type": "string"
                },
                "tenant_name": {
                    "description": "承租户名",
                    "type": "string"
                },
                "updated_at": {
                    "description": "创建时间戳",
                    "type": "integer"
                }
            }
        },
        "models.Token": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "token uuid",
                    "type": "string"
                },
                "expires_in": {
                    "description": "存活时间3600秒 1时间",
                    "type": "integer"
                },
                "id": {
                    "description": "token id",
                    "type": "integer"
                },
                "refresh_token": {
                    "description": "刷新token uuid",
                    "type": "string"
                },
                "scope": {
                    "description": "范围",
                    "type": "string"
                },
                "token_type": {
                    "description": "token类型",
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "required": [
                "email",
                "mobile_phone",
                "password",
                "tenant_id",
                "user_name"
            ],
            "properties": {
                "created_at": {
                    "description": "创建时间戳",
                    "type": "integer"
                },
                "email": {
                    "description": "用户邮箱",
                    "type": "string"
                },
                "first_name": {
                    "description": "用户名",
                    "type": "string"
                },
                "gender": {
                    "description": "性别",
                    "type": "string"
                },
                "id": {
                    "description": "用户id",
                    "type": "integer"
                },
                "last_name": {
                    "description": "用户名",
                    "type": "string"
                },
                "mobile_phone": {
                    "description": "移动电话",
                    "type": "string"
                },
                "password": {
                    "description": "用户密码",
                    "type": "string"
                },
                "tenant_id": {
                    "description": "tenant_id",
                    "type": "string"
                },
                "updated_at": {
                    "description": "创建时间戳",
                    "type": "integer"
                },
                "user_name": {
                    "description": "用户名",
                    "type": "string"
                },
                "uuid": {
                    "description": "用户uuid",
                    "type": "string"
                }
            }
        },
        "swag.ResultContCaptcha": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "返回的数据",
                    "$ref": "#/definitions/models.CaptchaResponse"
                },
                "msg": {
                    "description": "报错信息",
                    "type": "string",
                    "example": "错误"
                },
                "statusCode": {
                    "description": "代码,0:成功，非0:失败",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "swag.ResultContChangePass": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "返回的数据",
                    "$ref": "#/definitions/models.User"
                },
                "msg": {
                    "description": "报错信息",
                    "type": "string",
                    "example": "错误"
                },
                "statusCode": {
                    "description": "代码,0:成功，非0:失败",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "swag.ResultContCreatedTenant": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "返回的数据",
                    "$ref": "#/definitions/models.Tenant"
                },
                "msg": {
                    "description": "报错信息",
                    "type": "string",
                    "example": "错误"
                },
                "statusCode": {
                    "description": "代码,0:成功，非0:失败",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "swag.ResultContDeleteTenantById": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "返回的数据",
                    "$ref": "#/definitions/models.Tenant"
                },
                "msg": {
                    "description": "报错信息",
                    "type": "string",
                    "example": "错误"
                },
                "statusCode": {
                    "description": "代码,0:成功，非0:失败",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "swag.ResultContGetCaptchaImage": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "返回的数据",
                    "$ref": "#/definitions/models.CaptchaResponse"
                },
                "msg": {
                    "description": "报错信息",
                    "type": "string",
                    "example": "错误"
                },
                "statusCode": {
                    "description": "代码,0:成功，非0:失败",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "swag.ResultContGetTenantById": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "返回的数据",
                    "$ref": "#/definitions/models.Tenant"
                },
                "msg": {
                    "description": "报错信息",
                    "type": "string",
                    "example": "错误"
                },
                "statusCode": {
                    "description": "代码,0:成功，非0:失败",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "swag.ResultContGetTenantByName": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "返回的数据",
                    "$ref": "#/definitions/models.Tenant"
                },
                "msg": {
                    "description": "报错信息",
                    "type": "string",
                    "example": "错误"
                },
                "statusCode": {
                    "description": "代码,0:成功，非0:失败",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "swag.ResultContGetTenantList": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "返回的数据",
                    "$ref": "#/definitions/models.Tenant"
                },
                "msg": {
                    "description": "报错信息",
                    "type": "string",
                    "example": "错误"
                },
                "statusCode": {
                    "description": "代码,0:成功，非0:失败",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "swag.ResultContGoods": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "返回的数据",
                    "$ref": "#/definitions/models.Goods"
                },
                "msg": {
                    "description": "报错信息",
                    "type": "string",
                    "example": "错误"
                },
                "statusCode": {
                    "description": "代码,0:成功，非0:失败",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "swag.ResultContGoodsList": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "商品列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Goods"
                    }
                },
                "msg": {
                    "description": "报错信息",
                    "type": "string",
                    "example": "错误"
                },
                "statusCode": {
                    "description": "代码,0:成功，非0:失败",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "swag.ResultContSingIn": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "返回的数据",
                    "$ref": "#/definitions/models.User"
                },
                "msg": {
                    "description": "报错信息",
                    "type": "string",
                    "example": "错误"
                },
                "statusCode": {
                    "description": "代码,0:成功，非0:失败",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "swag.ResultContSingUp": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "返回的数据",
                    "$ref": "#/definitions/models.User"
                },
                "msg": {
                    "description": "报错信息",
                    "type": "string",
                    "example": "错误"
                },
                "statusCode": {
                    "description": "代码,0:成功，非0:失败",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "swag.ResultContTest": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "返回的数据",
                    "$ref": "#/definitions/models.User"
                },
                "msg": {
                    "description": "报错信息",
                    "type": "string",
                    "example": "错误"
                },
                "statusCode": {
                    "description": "代码,0:成功，非0:失败",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "swag.ResultContToken": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "返回的数据",
                    "$ref": "#/definitions/models.Token"
                },
                "msg": {
                    "description": "报错信息",
                    "type": "string",
                    "example": "错误"
                },
                "statusCode": {
                    "description": "代码,0:成功，非0:失败",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "swag.ResultContUpdateTenant": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "返回的数据",
                    "$ref": "#/definitions/models.Tenant"
                },
                "msg": {
                    "description": "报错信息",
                    "type": "string",
                    "example": "错误"
                },
                "statusCode": {
                    "description": "代码,0:成功，非0:失败",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "swag.ResultContUserByEmail": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "返回的数据",
                    "$ref": "#/definitions/models.User"
                },
                "msg": {
                    "description": "报错信息",
                    "type": "string",
                    "example": "错误"
                },
                "statusCode": {
                    "description": "代码,0:成功，非0:失败",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "swag.ResultContUserById": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "返回的数据",
                    "$ref": "#/definitions/models.User"
                },
                "msg": {
                    "description": "报错信息",
                    "type": "string",
                    "example": "错误"
                },
                "statusCode": {
                    "description": "代码,0:成功，非0:失败",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "swag.ResultContUserByName": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "返回的数据",
                    "$ref": "#/definitions/models.User"
                },
                "msg": {
                    "description": "报错信息",
                    "type": "string",
                    "example": "错误"
                },
                "statusCode": {
                    "description": "代码,0:成功，非0:失败",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "swag.ResultContUserByTenantId": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "返回的数据",
                    "$ref": "#/definitions/models.User"
                },
                "msg": {
                    "description": "报错信息",
                    "type": "string",
                    "example": "错误"
                },
                "statusCode": {
                    "description": "代码,0:成功，非0:失败",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "swag.ResultContVerifyCaptcha": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "返回的数据",
                    "$ref": "#/definitions/models.CaptchaResponse"
                },
                "msg": {
                    "description": "报错信息",
                    "type": "string",
                    "example": "错误"
                },
                "statusCode": {
                    "description": "代码,0:成功，非0:失败",
                    "type": "integer",
                    "example": 0
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "token",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:9090",
	BasePath:    "/v1",
	Schemes:     []string{},
	Title:       "XXXX项目名称-Swagger Example API",
	Description: "XXXX项目描述",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
